apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: samprati97/my-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "terraform-20250210133316976400000001.cw34ekqygfuu.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "mydb"
